import event1Svg from '../assets/events/event1.svg';
import defaultevent from '../assets/events/defaultevent.svg';

export const EVENTS = [
  {
    id: 1,
    past: false,
    timestamp: '2026-05-05',
    date: '5 Mayıs',
    month: 'Mayıs 2026',
    title: '“Eğitim ve Gelişim” Alanında Kariyer Yolları',
    location: 'İstanbul, TR',
    focus: 'Conference',
    desc: 'Teknoloji ve eğitimin kesiştiği noktada kariyerinizi nasıl şekillendirebilirsiniz? Eğitim dünyasında kariyer basamaklarını nasıl tırmanacağınızı keşfedin! Eğitim teknolojilerinden öğretim tasarımına kadar geniş bir yelpazede yeni nesil kariyer fırsatlarını uzman bakış açısıyla inceliyoruz.',
    img: defaultevent,
    formLink: '#',
    link: '#',
  },
  {
    id: 2,
    past: false,
    timestamp: '2026-05-06',
    date: '6 Mayıs',
    month: 'Mayıs 2026',
    title: 'Vapurda Şirketler Zirvesi',
    location: 'Üsküdar Belediyesi - Vapur Turu',
    focus: 'Career Development',
    desc: 'Bu zirvede girişimcileri, teknoloji liderlerini ve vizyoner şirketleri bir araya getiriyoruz. Alışılmışın dışında bir atmosferde ağ kurma (networking) fırsatı bulacağınız bu özel etkinlikte; panel oturumlarından stratejik iş birliklerine kadar dolu bir içerik sizi bekliyor.',
    img: defaultevent,
    formLink: '#',
    link: '#',
  },
  {
    id: 3,
    past: false,
    timestamp: '2026-04-25',
    date: '25 Nisan',
    month: 'Nisan 2026',
    title: 'Architecture Of Tomorrow: Session-1',
    location: 'Online',
    focus: 'Tech Talk',
    desc: 'Bu seri,değişen teknolojiler karşısında nasıl düşüneceğimizi konuşuyor. 1. Oturumda Patterns, Trade-offs & Design Thinking konuları konuşulacaktır.',
    img: event1Svg,
    formLink: 'https://forms.gle/Vs2e1ZCcR1My4yiQ7',
    link: '#',
  },
  {
    id: 4,
    past: false,
    timestamp: '2026-05-02',
    date: '2 Mayıs',
    month: 'Mayıs 2026',
    title: 'Architecture Of Tomorrow: Session-2',
    location: 'Online',
    focus: 'Tech Talk',
    desc: 'Bu seri,değişen teknolojiler karşısında nasıl düşüneceğimizi konuşuyor. 2. Oturumda; AI Agents,Platform Engineering konuları konuşulacaktır.',
    img: event1Svg,
    formLink: 'https://forms.gle/YPdQBA6gUta5TeQU6',
    link: '#',
  },
 {
    id: 5,
    past: false,
    timestamp: '2026-05-09',
    date: '9 Mayıs',
    month: 'Mayıs 2026',
    title: 'Architecture Of Tomorrow: Session-3',
    location: 'Online',
    focus: 'Tech Talk',
    desc: 'Bu seri, tek tek teknolojileri öğretmekten çok, değişen teknolojiler karşısında nasıl düşüneceğimizi konuşuyor. 3. Oturum Hala planlanmaktadır.',
    img: event1Svg,
    formLink: '#',
    link: '#',
  }
];

export const FILTER_BUTTONS = [
  { label: 'Tümü',                value: 'all',                  focusKey: 'all' },
  { label: 'AI',                  value: 'AI',                   focusKey: 'AI' },
  { label: 'Tech Talk / Meetup',  value: 'Tech Talk',            focusKey: 'Tech Talk' },
  { label: 'Career Development',  value: 'Career Development',   focusKey: 'Career Development' },
  { label: 'Conference',          value: 'Conference',           focusKey: 'Conference' },
  { label: 'Dev',                 value: 'Dev',                  focusKey: 'Dev' },
  { label: 'Community Building',  value: 'Community Building',   focusKey: 'Community Building' },
];

export const FOCUS_CLASSES = {
  'all': {
    text: 'text-[#f9ab00]',
    bg: 'bg-[#f9ab00]/10',
    badgeText: 'text-[#f9ab00]',
    activeBtn: 'bg-[#f9ab00] border-[#f9ab00] text-black',
    hoverBtn: 'hover:border-[#f9ab00] hover:text-[#f9ab00]',
    primaryBtn: 'bg-[#f9ab00] text-black hover:bg-[#f9ab00]/90',
  },
  'AI': {
    text: 'text-[#f9ab00]',
    bg: 'bg-[#f9ab00]/10',
    badgeText: 'text-[#f9ab00]',
    activeBtn: 'bg-[#f9ab00] border-[#f9ab00] text-black',
    hoverBtn: 'hover:border-[#f9ab00] hover:text-[#f9ab00]',
    primaryBtn: 'bg-[#f9ab00] text-black hover:bg-[#f9ab00]/90',
  },
  'Tech Talk': {
    text: 'text-[#ea4335]',
    bg: 'bg-[#ea4335]/10',
    badgeText: 'text-[#ea4335]',
    activeBtn: 'bg-[#ea4335] border-[#ea4335] text-white',
    hoverBtn: 'hover:border-[#ea4335] hover:text-[#ea4335]',
    primaryBtn: 'bg-[#ea4335] text-white hover:bg-[#ea4335]/90',
  },
  'Career Development': {
    text: 'text-[#34a853]',
    bg: 'bg-[#34a853]/10',
    badgeText: 'text-[#34a853]',
    activeBtn: 'bg-[#34a853] border-[#34a853] text-white',
    hoverBtn: 'hover:border-[#34a853] hover:text-[#34a853]',
    primaryBtn: 'bg-[#34a853] text-white hover:bg-[#34a853]/90',
  },
  'Conference': {
    text: 'text-[#f9ab00]',
    bg: 'bg-[#f9ab00]/10',
    badgeText: 'text-[#f9ab00]',
    activeBtn: 'bg-[#f9ab00] border-[#f9ab00] text-black',
    hoverBtn: 'hover:border-[#f9ab00] hover:text-[#f9ab00]',
    primaryBtn: 'bg-[#f9ab00] text-black hover:bg-[#f9ab00]/90',
  },
  'Dev': {
    text: 'text-[#4285f4]',
    bg: 'bg-[#4285f4]/10',
    badgeText: 'text-[#4285f4]',
    activeBtn: 'bg-[#4285f4] border-[#4285f4] text-white',
    hoverBtn: 'hover:border-[#4285f4] hover:text-[#4285f4]',
    primaryBtn: 'bg-[#4285f4] text-white hover:bg-[#4285f4]/90',
  },
  'Community Building': {
    text: 'text-[#ea4335]',
    bg: 'bg-[#ea4335]/10',
    badgeText: 'text-[#ea4335]',
    activeBtn: 'bg-[#ea4335] border-[#ea4335] text-white',
    hoverBtn: 'hover:border-[#ea4335] hover:text-[#ea4335]',
    primaryBtn: 'bg-[#ea4335] text-white hover:bg-[#ea4335]/90',
  },
  'past': {
    text: 'text-gray-500',
    bg: 'bg-gray-500/10',
    badgeText: 'text-gray-400',
    activeBtn: 'bg-gray-600 border-gray-600 text-white',
    hoverBtn: 'hover:border-gray-400 hover:text-gray-400',
    primaryBtn: 'bg-gray-700 text-gray-300 cursor-not-allowed',
  },
};

export const CARD_POS = {
  '0': 'w-[300px] md:w-[360px] z-[5] opacity-100 [filter:blur(0px)] shadow-[0_0_0_1px_rgba(249,171,0,0.28),0_40px_80px_rgba(0,0,0,.7)] [transform:translateX(0)_scale(1)_translateZ(0)]',
  '1': 'w-[280px] md:w-[320px] z-[4] opacity-[.65] [filter:blur(1.5px)] [transform:translateX(220px)_scale(.8)_translateZ(-60px)] md:[transform:translateX(340px)_scale(.82)_translateZ(-60px)]',
  '2': 'w-[280px] md:w-[320px] z-[1] md:z-[3] opacity-0 md:opacity-[.32] pointer-events-none md:pointer-events-auto [filter:blur(3px)] [transform:translateX(0)_scale(.5)_translateZ(-200px)] md:[transform:translateX(580px)_scale(.66)_translateZ(-120px)]',
  '-1': 'w-[280px] md:w-[320px] z-[4] opacity-[.65] [filter:blur(1.5px)] [transform:translateX(-220px)_scale(.8)_translateZ(-60px)] md:[transform:translateX(-340px)_scale(.82)_translateZ(-60px)]',
  '-2': 'w-[280px] md:w-[320px] z-[1] md:z-[3] opacity-0 md:opacity-[.32] pointer-events-none md:pointer-events-auto [filter:blur(3px)] [transform:translateX(0)_scale(.5)_translateZ(-200px)] md:[transform:translateX(-580px)_scale(.66)_translateZ(-120px)]',
  '3': 'w-[280px] md:w-[320px] z-[1] opacity-0 pointer-events-none [transform:translateX(0)_scale(.5)_translateZ(-200px)]',
  '-3': 'w-[280px] md:w-[320px] z-[1] opacity-0 pointer-events-none [transform:translateX(0)_scale(.5)_translateZ(-200px)]',
};