
export const EVENTS = [
  {
    id: 1,
    past: true,
    date: 'Şub 20-21',
    month: 'Şubat 2026',
    title: 'Lorem Ipsum Summit',
    location: 'Las Vegas, ABD',
    focus: 'Affiliate Marketing',
    attending: false,
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua, ut enim ad minim veniam.',
    img: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80',
    formLink: '#',
    link: '#',
  },
  {
    id: 2,
    past: true,
    date: 'Mar 2-5',
    month: 'Mart 2026',
    title: 'Dolor Sit Amet Conf',
    location: 'Barcelona, İspanya',
    focus: 'Digital Marketing',
    attending: false,
    desc: 'Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore. Quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo.',
    img: 'https://images.unsplash.com/photo-1591115765373-5207764f72e7?w=800&q=80',
    formLink: '#',
    link: '#',
  },
  {
    id: 3,
    past: false,
    date: 'Mar 24-25',
    month: 'Mart 2026',
    title: 'Adipiscing Elite World',
    location: 'Dubai, BAE',
    focus: 'Affiliate Marketing',
    attending: true,
    desc: 'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident.',
    img: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80',
    formLink: '#',
    link: '#',
  },
  {
    id: 4,
    past: false,
    date: 'Nis 8-10',
    month: 'Nisan 2026',
    title: 'Tempor Incididunt Dev',
    location: 'San Francisco, ABD',
    focus: 'GameDev',
    attending: false,
    desc: 'Sunt in culpa qui officia deserunt mollit anim id est laborum. Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor.',
    img: 'https://images.unsplash.com/photo-1556438064-2d7646166914?w=800&q=80',
    formLink: '#',
    link: '#',
  },
  {
    id: 5,
    past: false,
    date: 'Nis 22-24',
    month: 'Nisan 2026',
    title: 'Magna Aliqua Summit',
    location: 'Londra, İngiltere',
    focus: 'Digital Marketing',
    attending: false,
    desc: 'Ut enim ad minim veniam quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor in reprehenderit.',
    img: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=800&q=80',
    formLink: '#',
    link: '#',
  },
  {
    id: 6,
    past: false,
    date: 'May 5-7',
    month: 'Mayıs 2026',
    title: 'Ullamco Laboris Europe',
    location: 'Amsterdam, Hollanda',
    focus: 'Influencer Marketing',
    attending: true,
    desc: 'Voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit.',
    img: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80',
    formLink: '#',
    link: '#',
  },
  {
    id: 7,
    past: false,
    date: 'May 18-19',
    month: 'Mayıs 2026',
    title: 'Commodo Consequat Con',
    location: 'Frankfurt, Almanya',
    focus: 'FinTech',
    attending: false,
    desc: 'Nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur lorem.',
    img: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?w=800&q=80',
    formLink: '#',
    link: '#',
  },
];

export const FOCUS_CLASSES = {
  'Affiliate Marketing': {
    text:        'text-ev-yellow',
    bg:          'bg-ev-yellow',
    badgeText:   'text-black',
    border:      'border-ev-yellow',
    bgFaint:     'bg-ev-yellow/[13%]',
    borderFaint: 'border-ev-yellow/[27%]',
    hoverBtn:    'hover:bg-ev-yellow/[15%] hover:border-ev-yellow hover:text-ev-yellow hover:shadow-[0_0_12px_rgba(249,171,0,0.2)]',
    activeBtn:   'bg-ev-yellow border-ev-yellow text-black',
    primaryBtn:  'bg-ev-yellow text-black hover:bg-[#e09800]',
  },
  'Digital Marketing': {
    text:        'text-ev-blue',
    bg:          'bg-ev-blue',
    badgeText:   'text-white',
    border:      'border-ev-blue',
    bgFaint:     'bg-ev-blue/[13%]',
    borderFaint: 'border-ev-blue/[27%]',
    hoverBtn:    'hover:bg-ev-blue/[15%] hover:border-ev-blue hover:text-ev-blue hover:shadow-[0_0_12px_rgba(66,133,244,0.2)]',
    activeBtn:   'bg-ev-blue border-ev-blue text-black',
    primaryBtn:  'bg-ev-blue text-white hover:brightness-90',
  },
  'FinTech': {
    text:        'text-ev-green',
    bg:          'bg-ev-green',
    badgeText:   'text-black',
    border:      'border-ev-green',
    bgFaint:     'bg-ev-green/[13%]',
    borderFaint: 'border-ev-green/[27%]',
    hoverBtn:    'hover:bg-ev-green/[15%] hover:border-ev-green hover:text-ev-green hover:shadow-[0_0_12px_rgba(52,168,83,0.2)]',
    activeBtn:   'bg-ev-green border-ev-green text-black',
    primaryBtn:  'bg-ev-green text-black hover:brightness-90',
  },
  'GameDev': {
    text:        'text-ev-red',
    bg:          'bg-ev-red',
    badgeText:   'text-black',
    border:      'border-ev-red',
    bgFaint:     'bg-ev-red/[13%]',
    borderFaint: 'border-ev-red/[27%]',
    hoverBtn:    'hover:bg-ev-red/[15%] hover:border-ev-red hover:text-ev-red hover:shadow-[0_0_12px_rgba(234,67,53,0.2)]',
    activeBtn:   'bg-ev-red border-ev-red text-black',
    primaryBtn:  'bg-ev-red text-black hover:brightness-90',
  },
  'Influencer Marketing': {
    text:        'text-ev-yellow',
    bg:          'bg-ev-yellow',
    badgeText:   'text-black',
    border:      'border-ev-yellow',
    bgFaint:     'bg-ev-yellow/[13%]',
    borderFaint: 'border-ev-yellow/[27%]',
    hoverBtn:    'hover:bg-ev-yellow/[15%] hover:border-ev-yellow hover:text-ev-yellow hover:shadow-[0_0_12px_rgba(249,171,0,0.2)]',
    activeBtn:   'bg-ev-yellow border-ev-yellow text-black',
    primaryBtn:  'bg-ev-yellow text-black hover:bg-[#e09800]',
  },
  'Mobile Marketing': {
    text:        'text-ev-blue',
    bg:          'bg-ev-blue',
    badgeText:   'text-white',
    border:      'border-ev-blue',
    bgFaint:     'bg-ev-blue/[13%]',
    borderFaint: 'border-ev-blue/[27%]',
    hoverBtn:    'hover:bg-ev-blue/[15%] hover:border-ev-blue hover:text-ev-blue hover:shadow-[0_0_12px_rgba(66,133,244,0.2)]',
    activeBtn:   'bg-ev-blue border-ev-blue text-black',
    primaryBtn:  'bg-ev-blue text-white hover:brightness-90',
  },
};


export const FILTER_BUTTONS = [
  { label: 'Tümü',       value: 'all',                  focusKey: 'Affiliate Marketing' },
  { label: 'Affiliate',  value: 'Affiliate Marketing',  focusKey: 'Affiliate Marketing' },
  { label: 'Digital',    value: 'Digital Marketing',    focusKey: 'Digital Marketing'   },
  { label: 'FinTech',    value: 'FinTech',              focusKey: 'FinTech'             },
  { label: 'GameDev',    value: 'GameDev',              focusKey: 'GameDev'             },
  { label: 'Influencer', value: 'Influencer Marketing', focusKey: 'Influencer Marketing'},
];

export const CARD_POS_DESKTOP = {
  '0':  'w-[360px] [transform:translateX(0)_scale(1)_translateZ(0)] opacity-100 z-[5] [filter:blur(0px)] shadow-[0_0_0_1px_rgba(249,171,0,0.28),0_40px_80px_rgba(0,0,0,.7)]',
  '1':  'w-[320px] [transform:translateX(340px)_scale(.82)_translateZ(-60px)] opacity-[.65] z-[4] [filter:blur(1.5px)]',
  '2':  'w-[320px] [transform:translateX(580px)_scale(.66)_translateZ(-120px)] opacity-[.32] z-[3] [filter:blur(3px)]',
  '-1': 'w-[320px] [transform:translateX(-340px)_scale(.82)_translateZ(-60px)] opacity-[.65] z-[4] [filter:blur(1.5px)]',
  '-2': 'w-[320px] [transform:translateX(-580px)_scale(.66)_translateZ(-120px)] opacity-[.32] z-[3] [filter:blur(3px)]',
  '3':  'w-[320px] [transform:translateX(0)_scale(.5)_translateZ(-200px)] opacity-0 z-[1] pointer-events-none',
  '-3': 'w-[320px] [transform:translateX(0)_scale(.5)_translateZ(-200px)] opacity-0 z-[1] pointer-events-none',
};

export const CARD_POS_MOBILE = {
  '0':  'w-[360px] [transform:translateX(0)_scale(1)_translateZ(0)] opacity-100 z-[5] [filter:blur(0px)] shadow-[0_0_0_1px_rgba(249,171,0,0.28),0_40px_80px_rgba(0,0,0,.7)]',
  '1':  'w-[320px] [transform:translateX(220px)_scale(.8)_translateZ(-60px)] opacity-[.65] z-[4] [filter:blur(1.5px)]',
  '2':  'w-[320px] [transform:translateX(0)_scale(.5)_translateZ(-200px)] opacity-0 z-[1] pointer-events-none',
  '-1': 'w-[320px] [transform:translateX(-220px)_scale(.8)_translateZ(-60px)] opacity-[.65] z-[4] [filter:blur(1.5px)]',
  '-2': 'w-[320px] [transform:translateX(0)_scale(.5)_translateZ(-200px)] opacity-0 z-[1] pointer-events-none',
  '3':  'w-[320px] [transform:translateX(0)_scale(.5)_translateZ(-200px)] opacity-0 z-[1] pointer-events-none',
  '-3': 'w-[320px] [transform:translateX(0)_scale(.5)_translateZ(-200px)] opacity-0 z-[1] pointer-events-none',
};