export const members = [
  {
    id: 1,
    name: "Sedef Beyza Tetik",
    title: "Lead Organizer ",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/sedef-tetik",
    photo: null,
  },
  {
    id: 2,
    name: "Fatih Serdar Erkan",
    title: "Co Organizer ",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/fatih-serdar-erkan",
    photo: null,
  },
    {
    id: 3,
    name: "Zeynepnaz Koç",
    title: "Secretary General",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/zeynepnaz-koç-5143a1329",
    photo: null,
  },
  {
    id: 4,
    name: "Bahar Işıklı",
    title: "Technical Team Lead",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/ibahar/",
    photo: null,
  },
  {
    id: 5,
    name: "Talha Dağ",
    title: "technical team member",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/talha-dağ-0337b9263",
    photo: null,
  },
  {
    id: 6,
    name: "Mehmet Emre Kızılkaya ",
    title: "Event team lead",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/mehmet-emre-kizilkaya-9a7954325/",
    photo: null,
  },
  {
    id: 7,
    name: "Esma Öztaş",
    title: "Event team member",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/esma-öztaş-296301247",
    photo: null,
  },
    {
    id: 8,
    name: "Nilvana Karabulut",
    title: "Event team member",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/nilvanakarabulut1",
    photo: null,
  },
    {
    id: 9,
    name: "Nisa Nur Erkan",
    title: "Sponsorship Team Lead",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/nisa-nur-erkan",
    photo: null,
  },
    {
    id: 10,
    name: "Muhammet Emin Balmuk",
    title: "Project Team Member",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/eminbalmuk",
    photo: null,
  },
    {
    id: 11,
    name: "Furkan Usul",
    title: "Project Team Member",
    email: "isim@sirket.com",
    linkedin: "https://www.linkedin.com/in/furkan-usul/",
    photo: null,
  },
];
